/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <BSW_Set_RPM/Set_Driving_Mode.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "ASW_FCA/FCA.h"
#include "ASW_Lane_Change/lane_change.h"
#include "ASW_Lane_Keeping/lane_keeping.h"
#include "BSW_PID/It_Handler.h"
#include "BSW_PID/Encoder.h"
#include "BSW_PID/GTM_ATOM_PWM.h"
#include "BSW_PID/STM_Interrupt.h"
#include "BSW_Car_State_Manager/car_state_manager.h"
#include "BSW_CAN/CanHandler.h"
#include "ASW_BCW/BCW.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
int turn_right_count = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /*-----초기화-----*/
    initIncrEnc();
    initGtmATomPwm();
    initPins();
    initPeripherals();
    initFCASTM();
    initLaneKeepSTM();

    setTargetSpeed(350, 350);

    while(1)
    {
        if( (newCautionLv == 4) && (carState.mode == DRIVING_STRAIGHT))
        {
            T1_rotation_Right();
            turn_right_count++;
        }

        if(turn_right_count >= 2 && /*LeftOffset > 300 &&*/ carState.mode == DRIVING_STRAIGHT)
        {
            complete_EDSS = TRUE;
            carState.stop = TRUE;
        }

        if(carState.lanefunc == LANE_CHANGE)
        {
            checkRightOffsetChange();
        }

        if(Lane_Keep_IT_Flag == TRUE)
        {
            lane_keep();
        }

        if(STM_IT_FLAG == TRUE)
        {
            Enc_10ms_Handler();
        }

        if(FCA_IT_FLAG == TRUE)
        {
            performFCA();
            transmitCanMessage(Motor_BrakeSta);
            transmitCanMessage(Motor_EmergencyAlarm);
            transmitCanMessage(Motor_WheelAngle);
            transmitCanMessage(Motor_LaneChange);
        }
    }
}
