/**********************************************************************************************************************
 * \file lane_keeping.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ASW_Lane_Keeping/lane_keeping.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LANE_KEEP_TIME_INTERVAL              30
#define ISR_PRIORITY_LANE_KEEP_STM           150
#define STM2                                 &MODULE_STM2

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
boolean Lane_Keep_IT_Flag = FALSE;
IfxStm_CompareConfig Lane_Keep_STMConf;
uint32 g_ticksFor25ms;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(isr_lane_keep, 0, ISR_PRIORITY_LANE_KEEP_STM);

volatile sint16 currentHeadingAngle = 0;
void lane_keep(void)
{
    Lane_Keep_IT_Flag = FALSE; //인터럽트 플래그 off

    Direction direction;

    currentHeadingAngle = getHeadingAngleError();

    if(carState.lanefunc == LANE_CHANGE)
    {
        IfxStm_increaseCompare(STM2, Lane_Keep_STMConf.comparator, (uint32)g_ticksFor25ms);
        return;
    }

    if((currentHeadingAngle > -5) && (currentHeadingAngle < 5))
    {
        carState.mode = DRIVING_STRAIGHT;
    }
    else
    {
        if(currentHeadingAngle > 5)
        {
            if(carState.stop == FALSE)
            {
                direction = Left;
            }
        }
        else if(currentHeadingAngle < -5)
        {
            if(carState.stop == FALSE)
            {
                direction = Right;
            }
        }

        if(carState.stop == FALSE)
        {
            set_turn(direction, 0.6);
        }
    }

    IfxStm_increaseCompare(STM2, Lane_Keep_STMConf.comparator, (uint32)g_ticksFor25ms);
}

void isr_lane_keep(void)
{
    Lane_Keep_IT_Flag = TRUE;
}

void initLaneKeepSTM(void)
{
    IfxStm_initCompareConfig(&Lane_Keep_STMConf);
    g_ticksFor25ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, LANE_KEEP_TIME_INTERVAL);

    Lane_Keep_STMConf.triggerPriority = ISR_PRIORITY_LANE_KEEP_STM;
    Lane_Keep_STMConf.typeOfService = IfxSrc_Tos_cpu0;
    Lane_Keep_STMConf.ticks = (uint32)g_ticksFor25ms;
    IfxStm_initCompare(STM2, &Lane_Keep_STMConf);
}
