/**********************************************************************************************************************
 * \file car_state_manager.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BSW_CAR_STATE_MANAGER_CAR_STATE_MANAGER_H_
#define BSW_CAR_STATE_MANAGER_CAR_STATE_MANAGER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
typedef enum {
    DRIVING_STRAIGHT,
    DRIVING_TURNING_LEFT,
    DRIVING_TURNING_RIGHT
}DrivingMode;

typedef enum
{
    LANE_KEEPING,
    LANE_CHANGE
}LaneFunc;

// 차량 상태 구조체
typedef struct {
    float32 currentSpeed;      // 현재 속도 (mm/s)
    float32 targetSpeed;       // 목표 속도 (mm/s)
    float32 leftWheelSpeed;    // 좌측 바퀴 속도 (mm/s)
    float32 rightWheelSpeed;   // 우측 바퀴 속도 (mm/s)
    float32 baseSpeed;         // 차체의 속도
    DrivingMode mode;          // 현재 주행 모드 (직진 / 회전)
    boolean stop;              // 정지 여부 (TRUE = 정지)
    LaneFunc lanefunc;         // 차선 관련 기능
    boolean emergencyBrake;    // 급브레이크 여부
} CarState;

extern CarState carState;
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


#endif /* BSW_CAR_STATE_MANAGER_CAR_STATE_MANAGER_H_ */
